### ISSUE TITLE
Make it more self explanatory

### ISSUE THREAD

**Issue by mspykerez** [BigWigsMods/BigWigs_Voice#10]
Can you make this module more like DBM_VEM where it isn't limited to speak boss abilities to text-to-speech but it actually tells you what to do, like 'spread' 'kill adds' 'move out of...' 'move into...' 'stack' 'run away' etc.

**Comment by sehra** [comment]
I don't think it would fit the theme of BigWigs which I feel is to tell you what is happening, not what you should do.

Some changes could be fine though, it already says "under you" for some of the abilities.

**Comment by nebularg** [comment]
Right now, you could do this yourself by adding some voiced sounds for "what to do" actions to LibSharedMedia so you can set them as a custom sound (unchecking voice).

There are some plans to categorize sound events (underyou/interrupt/etc) to make what you're asking easier to do.

**Comment by toychristopher** [comment]
I also would like this. I mainly want to add a voice that says stack or spread. So if I add it to LibSharedMedia I can go through BigWigs and change the sound there? Would I actually even need Voice at that point?

**Comment by sehra** [comment]
You wouldn't need Voice in that case, BigWigs uses LibSharedMedia directly.
