### ISSUE TITLE
Make a way to disable all voice checkboxes

### ISSUE THREAD

**Issue by jgz** [BigWigsMods/BigWigs_Voice#14]
It would be real nice to have a way to mass uncheck all of the voice check boxes so that you can only turn voice on for the things you want it for.

**Comment by sehra** [comment]
This would be a feature request for [BigWigs](https://github.com/BigWigsMods/BigWigs).

**Comment by jgz** [comment]
Ok,  I posted in there instead.  Feel free to close this.
