### ISSUE TITLE
Gestation not making noise on Vectis

### ISSUE THREAD

**Issue by MikeRixWolfe** [BigWigsMods/BigWigs_Voice#16]
In mythic Uldir tonight progressing on vectis and Gestation doesnt have an audio queue which makes it harder to be on top of add spawns to burn them

**Comment by MikeRixWolfe** [comment]
My setttings
![image](https://user-images.githubusercontent.com/16833/46888165-9c9fe000-ce57-11e8-87e5-7b2b869b6703.png)

**Comment by sehra** [comment]
Moved Gestate to general warning, it was personal before.
