### ISSUE TITLE
bigwigs voice turned all into chinese

### ISSUE THREAD

**Issue by ssateneth** [BigWigsMods/BigWigs_Voice#17]
i opened wow today and all my bigwigs voice turned into chinese. whats up with that? please revert to english

**Comment by sehra** [comment]
Looks like a Chinese translation has been published with the same name. This addon is still in English.

**Comment by nebularg** [comment]
I pm'd the author asking to rename it and update the toc. Also poked a Curse guy to moderate it until it gets fixed.
