### ISSUE TITLE
Spanish

### ISSUE THREAD

**Issue by jacho981** [BigWigsMods/BigWigs_Voice#20]
Is it possible to make a spanish version of this addon? Maybe i can help in some way. Me and many of our friends would like to switch to bigwigs, but since there's not an spanish voice addon for it we're kinda stuck with DBM...
Is it just a matter of replacing the english .ogg files with spanish ones?

Thx for your time.

**Comment by sehra** [comment]
I can take a look at making a Spanish version this weekend.

**Comment by jacho981** [comment]
Thx! I know u probably have a lot of work now with 8.2 and spanish version is not a priority right now. So its much appreciated. Is there anyway i can find out when the version is released? Like a discord or something?  Like where do you announce releases? Thx again.

**Comment by sehra** [comment]
It will be published to https://www.curseforge.com/wow/addons/bigwigs-voice-es, pending review from someone at Curse. Should show up in the Twitch Client as well after that. For now only sounds from the raids are available, will add the dungeons soon.

**Comment by jacho981** [comment]
thx so much, amazing job you do for the community

**Comment by jacho981** [comment]
what channel goes the voice to?

**Comment by sehra** [comment]
It goes to the Master channel, just like BigWigs. The addon was approved so you can try it out.

**Comment by jacho981** [comment]
yeah, i tried it on the jaina kill, it gave us luck ^^ have to try it further tho. will try raising the master volume and lowering the other channels. cant wait to use it on m+ dungeons as soon as it's ready <3

**Comment by sehra** [comment]
Spanish is now complete with sounds for dungeons as well as the new raid.
