### ISSUE TITLE
PlaySoundFile Error - Invalid fileDataID for sound.

### ISSUE THREAD

**Issue by jdtemple** [BigWigsMods/BigWigs_Voice#22]
I'm getting some voice errors, so far in Waycrest Manor:

Message: Interface\AddOns\BigWigs_Voice\Core.lua:19: PlaySoundFile Error - Invalid fileDataID for sound.
Time: Sun Jun 30 13:17:27 2019
Count: 3
Stack: Interface\AddOns\BigWigs_Voice\Core.lua:19: PlaySoundFile Error - Invalid fileDataID for sound.
[C]: in function `PlaySoundFile'
Interface\AddOns\BigWigs_Voice\Core.lua:19: in function `v'
Interface\AddOns\BigWigs\Loader.lua:937: in function `SendMessage'
Interface\AddOns\BigWigs_Core\BossPrototype.lua:2325: in function `PlaySound'
...e\AddOns\LittleWigs\BfA\WaycrestManor\Heartsbane.lua:72: in function `?'
Interface\AddOns\BigWigs_Core\BossPrototype.lua:456: in function <Interface\AddOns\BigWigs_Core\BossPrototype.lua:422>

Locals: (*temporary) = "Interface\AddOns\BigWigs_Voice\Sounds\260703.ogg"
(*temporary) = "Master"

Message: Interface\AddOns\BigWigs_Voice\Core.lua:19: PlaySoundFile Error - Invalid fileDataID for sound.
Time: Sun Jun 30 13:28:05 2019
Count: 1
Stack: Interface\AddOns\BigWigs_Voice\Core.lua:19: PlaySoundFile Error - Invalid fileDataID for sound.
[C]: in function `PlaySoundFile'
Interface\AddOns\BigWigs_Voice\Core.lua:19: in function `v'
Interface\AddOns\BigWigs\Loader.lua:937: in function `SendMessage'
Interface\AddOns\BigWigs_Core\BossPrototype.lua:2325: in function `PlaySound'
...erface\AddOns\LittleWigs\BfA\WaycrestManor\Trash.lua:303: in function `?'
Interface\AddOns\BigWigs_Core\BossPrototype.lua:456: in function <Interface\AddOns\BigWigs_Core\BossPrototype.lua:422>

Locals: (*temporary) = "Interface\AddOns\BigWigs_Voice\Sounds\278474.ogg"
(*temporary) = "Master"

**Comment by alphagamereu** [comment]
I'm also getting the same errors that is preventing bigwigs from playing any alarm or alert sounds. Here's my bugsack: 

60x BigWigs_Voice\Core.lua:19: PlaySoundFile Error - Invalid fileDataID for sound.
[C]: in function `PlaySoundFile'
BigWigs_Voice\Core.lua:19: in function `v'
BigWigs\Loader.lua:937: in function `SendMessage'
BigWigs_Core\BossPrototype.lua:2325: in function `PlaySound'
...aceBigWigs_BattleOfDazaralor\Mekkatorque.lua:283: in function `?'
BigWigs_Core\BossPrototype.lua:456: in function <BigWigs_Core\BossPrototype.lua:422>

Locals:
InCombatSkipped


Issue is annoying as hell and would appreciate a fix at your earliest convenience, much appreciated!

**Comment by sehra** [comment]
I tagged the alpha as release 8.2.0.1, should show up on Curse/Twitch shortly.
