### ISSUE TITLE
Shadowlands?

### ISSUE THREAD

**Issue by spamwax** [BigWigsMods/BigWigs_Voice#27]
Will this be updated for Shadowlands?
Do you guys use any utility/script to automatically convert the name of debuff/abilities to OGG files?

**Comment by nebularg** [comment]
Yes, it usually gets updated after modules are finalized. The [scripts](https://github.com/BigWigsMods/BigWigs_Voice/tree/master/Tools) are included in the repo.

**Comment by sehra** [comment]
Yes, it will be updated for Shadowlands.

The generation of OGG files is mostly automated, but I still have to go through the BigWigs modules to pick which spells that should get a voice callout and what it should say.

tools/generate.txt: reads the spells-*.txt and generate WAV files using text-to-speech
tools/encode.txt: encodes all WAV files to OGG

**Comment by spamwax** [comment]
thank you for your responses
