### ISSUE TITLE
No voice in Castle Natharia

### ISSUE THREAD

**Issue by hardtofin** [BigWigsMods/BigWigs_Voice#28]
Using latest build of BW - 189 and latest BW voice - 9.0.2.2 but have no voice calls at all whilst inside the newest SL raid Castle Natharia.

Bigwigs countdown works, just no voice calling on abilities.

**Comment by sehra** [comment]
The latest version 9.0.2.2 have the sounds for Castle Nathria. Did you close and restart after updating?

Try the following to see if one of the newer sounds can be played:
`/script PlaySoundFile("Interface\\AddOns\\BigWigs_Voice\\Sounds\\-21953.ogg", "Master")`

**Comment by hardtofin** [comment]
I did close and restart.  I will check again tomorrow when i am back in the raid.  It did sporadically work for a couple of pulls and then stopped working again.

I downloaded the version from github which had an extra folder called "sounds", i will test this tomorrow.

**Comment by hardtofin** [comment]
All working now.  Thanks.
