### ISSUE TITLE
New installs = ALL voice enabled by default =/

### ISSUE THREAD

**Issue by Gewdz** [BigWigsMods/BigWigs_Voice#35]
Is it possible that perhaps there is a disable all button. Or have them all off by default. 
I personally found it time consuming to have to disable all the ones i don't want on. This would include all the trash mobs. 
I can't be the only one.
Are there features like this I am overlooking? 

Are there other voice options available? 

Thanks for the good work.

**Comment by sehra** [comment]
See #34. This is controlled by [BigWigs](https://github.com/BigWigsMods/BigWigs).
