### ISSUE TITLE
Plans to support four returning m+ dungeons

### ISSUE THREAD

**Issue by tynanseltzer** [BigWigsMods/BigWigs_Voice#36]
Hi! It doesn't appear there are any ability names for the four returning dungeons in the DF season 1 m+ cycle. Are there plans to add them? Absolutely love this addon, and am bricking keys without it! Thanks!

Edit -- Appears they are in COS, but not Temple?

**Comment by sehra** [comment]
Yes, I will add the missing dungeons.
