### ISSUE TITLE
Ruby Life Pools - Kokia Blazehoof

### ISSUE THREAD

**Issue by CaptainCompete** [BigWigsMods/BigWigs_Voice#38]
When the fire add casts "Roaring Blaze" I don't get a voice warning even though "Voice" is ticked

**Comment by sehra** [comment]
It will be included in the next update.

**Comment by CaptainCompete** [comment]
thanks guys, while at it, how about adding all interruptable casts? there's quite a few mobs in halls of valor and noktua offensive that have quite harmless casts at lower levels but at key level 22+ with fortified and raging, they become one shots
