### ISSUE TITLE
Missing mythic guldan abilities

### ISSUE THREAD

**Issue by xeropresence** [BigWigsMods/BigWigs_Voice#5]
Looks like all the abilities in phase 3 when illidan is up are currently unvoiced.

**Comment by sehra** [comment]
The abilities were probably not in BigWigs at the time I created the sound files. I'll take a look at adding what's missing.

**Comment by xeropresence** [comment]
What do you use to generate the voice files, i'd like to have these in for tuesday.

**Comment by sehra** [comment]
Fixed.

The sounds files are generated with Windows Speech Synthesis, using the Zira voice.
