### ISSUE TITLE
Voices are so quiet I can't hear them over the combat sounds in a raid

### ISSUE THREAD

**Issue by hickeroar** [BigWigsMods/BigWigs_Voice#6]
Unfortunately I can't hear the voices at all over the general sounds of combat in a raid. I tank, and there's so much general melee noise up by the boss that the addon is nearly useless. I would really love for this to be useful, but I can't figure out if there's a way to either raise the voice volume, or to somehow lower just the combat sound level.

I think it would be very useful if you could export the ogg files with a much higher output level or something along those lines. I believe Audacity can batch update a whole bunch of files at once and amplify them. https://forum.xda-developers.com/showpost.php?s=edfa5b35d2b9dde60174f609e21dd165&p=39857842&postcount=2

**Comment by hickeroar** [comment]
In Audacity you can also use **File -> Edit Chains** to make a chain for ogg amplification. I've done this as a test locally with a 10db boost, and it did update every ogg file to be louder. I haven't been able to test it in-game yet though to see if it's loud enough.

**Comment by sehra** [comment]
Under System/Sound, it might be possible to increase the Master volume while lowering the Sound volume. The voice files are played on the Master channel.

**Comment by hickeroar** [comment]
Do the combat sounds not play over the master channel?

**Comment by funkydude** [comment]
If by combat sounds you mean game sound effects then no.

**Comment by sehra** [comment]
I think the game sounds play over the SFX channel, which is just marked "Sound" in the settings.
