### ISSUE TITLE
Winds pronunciation incorrect

### ISSUE THREAD

**Issue by steev** [BigWigsMods/BigWigs_Voice#8]
The TTS seems to get winds wrong.  It uses the pronunciation like winding a clock, instead of a gust of wind.

The incorrect sounds seem to be 181956y, 218124 and 242017.

**Comment by sehra** [comment]
I've added support for IPA notation so should be fixed in the next update.

**Comment by layday** [comment]
Where was support for IPA added?  The soundfile generation logic appears to be entirely absent from the repo, what makes outside contributions very difficult.

**Comment by sehra** [comment]
The syntax for IPA notation isn't set in stone, but for now it would be winds=wɪndz. To add or update sounds, edit the file under tools/sounds.txt.

I'll see if I can include the script in the repository, Curse is a bit picky about which files types can be present for the packager to make a release.

**Comment by funkydude** [comment]
> I'll see if I can include the script in the repository, Curse is a bit picky about which files types can be present for the packager to make a release.

https://github.com/BigWigsMods/BigWigs/blob/master/.pkgmeta#L32

**Comment by layday** [comment]
> The syntax for IPA notation isn't set in stone, but for now it would be winds=wɪndz. To add or update sounds, edit the file under tools/sounds.txt.

Would IPA only be used for heteronyms?  How does the script distinguish between IPA and non-IPA text in sounds.txt?  Does it follow // convention?

**Comment by layday** [comment]
Oh do you literally type `winds=wɪndz`?  That works I guess.

**Comment by sehra** [comment]
Fixed the pronunciation of "winds" and added the LINQPad script used to automate TTS.
